---
# Source: bl45p-mo-ioc-90/templates/ioc.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name:  bl45p-mo-ioc-90
  namespace: bl45p
  labels:
    app: bl45p-mo-ioc-90
    beamline: bl45p
    ioc_version: "0.0.1-b0"
    is_ioc: "True"
data:
  ioc.boot.yaml: |
    # yaml-language-server: $schema=file://./ibek/pmac.ibek.entities.schema.json
    ioc_name: bl45p-mo-ioc-90
    description: motion IOC for the test beamline p45 in G13
    generic_ioc_image: ghcr.io/epics-containers/ioc-pmac-linux-developer:work

    entities:
      - type: pmac.PmacAsynSSHPort
        name: BRICK90port
        IP: 172.23.241.159

      - type: pmac.Geobrick
        name: BRICK90
        PORT: BRICK90port
        P: BL45P-MO-STEP-90
        numAxes: 8
        idlePoll: 100
        movingPoll: 500

      - type: pmac.DlsPmacAsynMotor
        name: STAGE90
        Controller: BRICK90
        axis: 2
        P: BL45P-MO-STAGE-90
        M: :THETA:TOP
        ACCL: 0.1
        MRES: 0.00000244
        VELO: 1
        VMAX: "1"
        HOMEVISSTR: Absolute Encoder
        EGU: mm
  start.sh: |
    #!/bin/bash
  
    #
    # generic kubernetes IOC startup script
    #
    this_dir=$(realpath $(dirname $0))
    TOP=$(realpath ${this_dir}/..)
    cd ${TOP}
  
    set -x -e
    exec ../ioc.sh
  version.txt: |
    IOC bl45p-mo-ioc-90 version 0.0.1-b0
---
# Source: bl45p-mo-ioc-90/templates/ioc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bl45p-mo-ioc-90
  namespace: bl45p
  labels:
    app: bl45p-mo-ioc-90
    beamline: bl45p
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
---
# Source: bl45p-mo-ioc-90/templates/ioc.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bl45p-mo-ioc-90
  namespace: bl45p
  labels:
    app: bl45p-mo-ioc-90
    beamline: bl45p
    ioc_version: "0.0.1-b0"
    is_ioc: "True"
  annotations:
    kubernetes.io/change-cause: 0.0.1-b0 deployed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bl45p-mo-ioc-90
  template:
    metadata:
      labels:
        app: bl45p-mo-ioc-90
        beamline: bl45p
        ioc_version: "0.0.1-b0"
        is_ioc: "True"
    spec:
      serviceAccountName: "bl45p-priv"
      hostNetwork: true
      terminationGracePeriodSeconds: 5 # nice to have quick restarts on IOCs
      volumes:
        
        - name: bl45p-mo-ioc-90
          persistentVolumeClaim:
            claimName: bl45p-mo-ioc-90
        - name: config-volume
          configMap:
            name: bl45p-mo-ioc-90
      containers:
      - name: bl45p-mo-ioc-90
        image: ghcr.io/epics-containers/ioc-pmac-run:1.2.0
        command:
          - bash
        args:
          - /repos/epics/ioc/config/start.sh
        volumeMounts:
        - name: config-volume
          mountPath: /repos/epics/ioc/config
        
        - name: bl45p-mo-ioc-90
          mountPath: /autosave
        stdin: true
        tty: true
        securityContext:
          allowPrivilegeEscalation: false
        resources: 
          limits:
            cpu: "3"
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 200Mi
        imagePullPolicy: Always
        env:
        - name: IOCSH_PS1
          value: "bl45p-mo-ioc-90 > "
        - name: IOC_NAME
          value: bl45p-mo-ioc-90
        - name: IOC_VERSION
          value: "0.0.1-b0"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beamline
                operator: In
                values:
                  - bl45p
      tolerations:
        - key: nodetype
          operator: Equal
          value: bl45p
          effect: NoSchedule
